/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokokecil;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import test.Message;
import static test.Message.judulJoption;
import static test.Message.txtJoption;
import test.failMessage;
import static test.failMessage.judulWarn;
import static test.failMessage.txtWarn;

/**
 *
 * @author VivoBook
 */
public class homeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form homeAdmin
     */
    
    public void mainKonten(){
        try{
            String sql = "SELECT COALESCE(COUNT(transaksi.no_nota),0) AS selesai FROM transaksi JOIN history_pengambilan ON transaksi.no_nota = history_pengambilan.no_nota "
                    + "WHERE history_pengambilan.status_pengambilan = 'diambil' AND DATE (transaksi.tgl_transaksi) = CURDATE() ";
            String sql1 = "SELECT COALESCE(COUNT(transaksi.no_nota),0) AS berlangsung FROM transaksi JOIN pengambilan ON transaksi.no_nota = pengambilan.no_nota "
                    + "WHERE pengambilan.status_pengambilan = 'belum' AND DATE (pengambilan.tanggal_pengambilan) = CURDATE() ";
            String sql2 = "SELECT COALESCE(COUNT(transaksi.no_nota),0) AS mendatang FROM transaksi JOIN pengambilan ON transaksi.no_nota = pengambilan.no_nota "
                    + "WHERE pengambilan.status_pengambilan = 'belum' AND DATE (pengambilan.tanggal_pengambilan) = CURDATE() + INTERVAL 1 DAY ";
            java.sql.Connection conn = new config().akses();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery(sql);
            java.sql.PreparedStatement pst1 = conn.prepareStatement(sql1);
            java.sql.ResultSet res1 = pst1.executeQuery(sql1);
            java.sql.PreparedStatement pst2 = conn.prepareStatement(sql2);
            java.sql.ResultSet res2 = pst2.executeQuery(sql2);
            while(res.next()){
                txtSelesai.setText(res.getString("selesai"));
                }
            while(res1.next()){
                txtBerlangsung.setText(res1.getString("berlangsung"));
                }
            while(res2.next()){
                txtMendatang.setText(res2.getString("mendatang"));
                }
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        DefaultTableModel modelT = new DefaultTableModel();
        modelT.addColumn("No Nota");
        modelT.addColumn("Customer");
        modelT.addColumn("Tanggal Ambil");
        modelT.addColumn("Jam Ambil");
        modelT.addColumn("Status Pembayaran");
        
        try{
            String sql = "SELECT transaksi.no_nota, transaksi.nama_cust, pengambilan.tanggal_pengambilan, pengambilan.jam, transaksi.statusTransaksi FROM transaksi "
                    + "JOIN pengambilan ON transaksi.no_nota = pengambilan.no_nota WHERE DATE (transaksi.tgl_transaksi) = CURDATE() ";
            java.sql.Connection conn = new config().akses();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery(sql);
            while(res.next()){
                modelT.addRow(new Object[]{res.getString(1),
                    res.getString(2),res.getString(3), res.getString(4)
                        , res.getString(5)
                });
            }
            tbRiwayatTr.setModel(modelT);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }
    
    public homeAdmin() {
        initComponents();
        mainKonten();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        pengambilan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        transact = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        HOME = new javax.swing.JPanel();
        txtBerlangsung = new javax.swing.JLabel();
        txtSelesai = new javax.swing.JLabel();
        txtMendatang = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRiwayatTr = new table.tabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pengambilanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(237, 224, 209));
        body.setPreferredSize(new java.awt.Dimension(1920, 1080));

        menuBar.setBackground(new java.awt.Color(57, 72, 12));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengambilan.setBackground(new java.awt.Color(234, 204, 154));
        pengambilan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengambilanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengambilanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengambilanMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PENGAMBILAN.png"))); // NOI18N

        javax.swing.GroupLayout pengambilanLayout = new javax.swing.GroupLayout(pengambilan);
        pengambilan.setLayout(pengambilanLayout);
        pengambilanLayout.setHorizontalGroup(
            pengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(pengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pengambilanLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pengambilanLayout.setVerticalGroup(
            pengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(pengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pengambilanLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuBar.add(pengambilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 430, 70));

        transact.setBackground(new java.awt.Color(234, 204, 154));
        transact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TRANSAKSI.png"))); // NOI18N

        javax.swing.GroupLayout transactLayout = new javax.swing.GroupLayout(transact);
        transact.setLayout(transactLayout);
        transactLayout.setHorizontalGroup(
            transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transactLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        transactLayout.setVerticalGroup(
            transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transactLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuBar.add(transact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 430, 70));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Group 47 (1).png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        menuBar.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        menuBar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 43.png"))); // NOI18N
        menuBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 42.png"))); // NOI18N
        menuBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        content.setBackground(new java.awt.Color(204, 255, 204));
        content.setPreferredSize(new java.awt.Dimension(1450, 1080));
        content.setLayout(new java.awt.CardLayout());

        HOME.setBackground(new java.awt.Color(237, 224, 209));
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBerlangsung.setBackground(new java.awt.Color(234, 204, 154));
        txtBerlangsung.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        txtBerlangsung.setForeground(new java.awt.Color(57, 72, 12));
        txtBerlangsung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBerlangsung.setToolTipText("");
        txtBerlangsung.setOpaque(true);
        HOME.add(txtBerlangsung, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 240, 120));

        txtSelesai.setBackground(new java.awt.Color(234, 204, 154));
        txtSelesai.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        txtSelesai.setForeground(new java.awt.Color(57, 72, 12));
        txtSelesai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSelesai.setToolTipText("");
        txtSelesai.setOpaque(true);
        HOME.add(txtSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 240, 120));

        txtMendatang.setBackground(new java.awt.Color(234, 204, 154));
        txtMendatang.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        txtMendatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMendatang.setToolTipText("");
        txtMendatang.setOpaque(true);
        HOME.add(txtMendatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 240, 120));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tbRiwayatTr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbRiwayatTr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(tbRiwayatTr);

        HOME.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 1140, 380));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mendatangHomeAdm.png"))); // NOI18N
        HOME.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PESANAN HARI INI.png"))); // NOI18N
        HOME.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RIWAYAT TRANSAKSI.png"))); // NOI18N
        HOME.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/berlangsungHomeAdm.png"))); // NOI18N
        jLabel7.setToolTipText("");
        HOME.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/selesaiHomeAdm.png"))); // NOI18N
        HOME.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 250));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borderrr.png"))); // NOI18N
        HOME.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        content.add(HOME, "card4");

        pengambilanPanel.setBackground(new java.awt.Color(237, 224, 209));
        pengambilanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pengambilanPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 880, -1));

        jTextField1.setBackground(new java.awt.Color(230, 187, 153));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pengambilanPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 320, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DAFTAR PESANAN.png"))); // NOI18N
        pengambilanPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Group 55.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pengambilanPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borderrr.png"))); // NOI18N
        pengambilanPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        content.add(pengambilanPanel, "card2");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1442, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(HOME);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_logoMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactMouseClicked
        // TODO add your handling code here:
        new transaksiFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactMouseClicked

    private void transactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactMouseEntered
        // TODO add your handling code here:
        transact.setBackground(new Color(177,113,62));
        transact.setOpaque(true);
    }//GEN-LAST:event_transactMouseEntered

    private void transactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactMouseExited
        // TODO add your handling code here:
        transact.setBackground(new Color(234,204,154));
    }//GEN-LAST:event_transactMouseExited

    private void pengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengambilanMouseClicked
        // TODO add your handling code here:
        new pengambilanFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pengambilanMouseClicked

    private void pengambilanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengambilanMouseEntered
        // TODO add your handling code here:
        pengambilan.setBackground(new Color(177,113,62));
        pengambilan.setOpaque(true);
    }//GEN-LAST:event_pengambilanMouseEntered

    private void pengambilanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengambilanMouseExited
        // TODO add your handling code here:
        pengambilan.setBackground(new Color(234,204,154));
    }//GEN-LAST:event_pengambilanMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        failMessage fail = new failMessage(this, true);
        judulWarn.setText("Logout Berhasil");
        txtWarn.setText("Kembali ke Login");
        fail.showAlert();
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel body;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel pengambilan;
    private javax.swing.JPanel pengambilanPanel;
    private table.tabel tbRiwayatTr;
    private javax.swing.JPanel transact;
    private javax.swing.JLabel txtBerlangsung;
    private javax.swing.JLabel txtMendatang;
    private javax.swing.JLabel txtSelesai;
    // End of variables declaration//GEN-END:variables
}
