package tokokecil;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import test.failMessage;
import static test.failMessage.judulWarn;
import static test.failMessage.txtWarn;

public class lupaPassword extends javax.swing.JFrame {
    Connection conn;
 ResultSet rs;
 PreparedStatement pst ;
    public lupaPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPertanyaan = new javax.swing.JTextField();
        txtJawaban = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginbutton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 420, -1, -1));

        txtUser.setBackground(new java.awt.Color(237, 223, 202));
        txtUser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtUser.setBorder(null);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 386, 380, 40));

        txtPertanyaan.setEditable(false);
        txtPertanyaan.setBackground(new java.awt.Color(237, 223, 202));
        txtPertanyaan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPertanyaan.setBorder(null);
        txtPertanyaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPertanyaanActionPerformed(evt);
            }
        });
        getContentPane().add(txtPertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 518, 370, 40));

        txtJawaban.setBackground(new java.awt.Color(237, 223, 202));
        txtJawaban.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtJawaban.setBorder(null);
        getContentPane().add(txtJawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 610, 370, 40));

        txtPassword.setBackground(new java.awt.Color(237, 223, 202));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 757, 370, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkButton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 610, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/submitButton.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Group 52.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Please (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPertanyaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPertanyaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPertanyaanActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String al = txtUser.getText();
        String sql = "select * from login where username ='"+al+"' ";
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/tokokue_new","root","");
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
        if(rs.next()){
            txtPertanyaan.setText(rs.getString(7));
            rs.close();
            pst.close();
            txtJawaban.setText("");
            txtPassword.setText("");
        }
        else{
            failMessage me = new failMessage(this, true);
            judulWarn.setText("Username Tidak Ditemukan");
            txtWarn.setText("Daftar akun hanya melalui owner");
            me.showAlert();
            //JOptionPane.showMessageDialog(null,"Username tidak ditemukan");
        }
        }catch(Exception e){
                     JOptionPane.showMessageDialog(null, e);
                     }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String a2 = txtJawaban.getText().trim();
if (a2.isEmpty()) {
    failMessage me = new failMessage(this, true);
            judulWarn.setText("Gagal Diproses!");
            txtWarn.setText("Isikan jawaban terlebih dahulu!");
            me.showAlert();
    //JOptionPane.showMessageDialog(null, "Silakan isi Jawaban Anda!");
} else {
    String sql = "SELECT * FROM login WHERE jawaban = ?";
    try {
        pst = conn.prepareStatement(sql);
        pst.setString(1, a2);
        rs = pst.executeQuery();
        if (rs.next()) {
            txtPassword.setText(rs.getString(5));
        } else {
            txtPassword.setText("");
            //JOptionPane.showMessageDialog(null, "Jawaban Anda Salah!");
            failMessage me = new failMessage(this, true);
            judulWarn.setText("Jawaban Anda Salah!");
            txtWarn.setText("Masukkan jawaban dengan benar");
            me.showAlert();
        }
    } catch (Exception e) {
        
    }
}

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPertanyaan;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
