/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokokecil;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import test.Message;
import static test.Message.judulJoption;
import static test.Message.txtJoption;

/**
 *
 * @author VivoBook
 */
public class pengambilan extends javax.swing.JFrame {

    /**
     * Creates new form pengambilan
     */
    
    public void tbDt(){
         DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Barang");
        model.addColumn("Qty");
        tbDetail.setModel(model);
    }
    
    public pengambilan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ambil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNtA = new javax.swing.JTextField();
        txtNamaA = new javax.swing.JTextField();
        tglTrA = new javax.swing.JTextField();
        tglAmbilA = new javax.swing.JTextField();
        jamA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAmbil = new table.tabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDetail = new table.tabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 224, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 860));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ambil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ambilbtn.png"))); // NOI18N
        ambil.setBorder(null);
        ambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilActionPerformed(evt);
            }
        });
        jPanel1.add(ambil, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 770, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back pelunasan.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barpelunasan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtNtA.setBackground(new java.awt.Color(237, 224, 209));
        txtNtA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNtA.setText("jTextField1");
        txtNtA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtNtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 40));

        txtNamaA.setBackground(new java.awt.Color(237, 224, 209));
        txtNamaA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNamaA.setText("jTextField1");
        txtNamaA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtNamaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, 40));

        tglTrA.setBackground(new java.awt.Color(237, 224, 209));
        tglTrA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tglTrA.setText("jTextField1");
        tglTrA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(tglTrA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, 40));

        tglAmbilA.setBackground(new java.awt.Color(237, 224, 209));
        tglAmbilA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tglAmbilA.setText("jTextField4");
        tglAmbilA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(tglAmbilA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 230, 40));

        jamA.setBackground(new java.awt.Color(237, 224, 209));
        jamA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jamA.setText("jTextField5");
        jamA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jamA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 230, 40));

        tbAmbil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAmbil.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tbAmbil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAmbilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAmbil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDetail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jScrollPane3.setViewportView(tbDetail);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 310, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borderrr.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 950, 916);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM `pengambilan` WHERE no_nota = '"+txtNtA.getText()+"'";       
            java.sql.Connection conn = new config().akses();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            pst.close();
            
            //JOptionPane.showMessageDialog(this, "berhasil diambil");
            Message me = new Message(this, true);
            judulJoption.setText("Berhasil Diambil!");
            txtJoption.setText("Proses Transaksi Selesai");
            me.showAlert();
            this.dispose();
                                              
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_ambilActionPerformed

    private void tbAmbilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAmbilMouseClicked
        // TODO add your handling code here:
        tbDt();
        int baris = tbAmbil.rowAtPoint(evt.getPoint());
        String id = tbAmbil.getValueAt(baris, 0).toString();
        String perbandingan = null;

        try{
            String sql = "SELECT identitas_pkt from detail_paket_tr where identitas_pkt = '"+id+"'";
            java.sql.Connection conn = new config().akses();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery(sql);
            while(res.next()){
                perbandingan = res.getString("identitas_pkt");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        if(id.equals(perbandingan)) {
            DefaultTableModel model = (DefaultTableModel) tbDetail.getModel();
            try{
                String sql = "SELECT detail_paket.id_barang, barang.nama_barang, detail_paket.qty FROM detail_paket_tr "
                + "JOIN detail_paket ON detail_paket_tr.identitas_pkt = detail_paket.identitas_pkt JOIN barang ON detail_paket.id_barang = barang.id_barang"
                + " where detail_paket_tr.identitas_pkt = '"+id+"'";
                java.sql.Connection conn = new config().akses();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                java.sql.ResultSet res = pst.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{res.getString(1),
                        res.getString(2),res.getString(3)
                    });
                }
                tbDetail.setModel(model);
            }catch(SQLException ex){

            }
        }
    }//GEN-LAST:event_tbAmbilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengambilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextField jamA;
    public static table.tabel tbAmbil;
    private table.tabel tbDetail;
    public static javax.swing.JTextField tglAmbilA;
    public static javax.swing.JTextField tglTrA;
    public static javax.swing.JTextField txtNamaA;
    public static javax.swing.JTextField txtNtA;
    // End of variables declaration//GEN-END:variables
}
